[package]
name = "borrow-graph"
version = "0.0.1"
authors = ["Libra Association <opensource@libra.org>"]
publish = false
edition = "2021"
license = "Apache-2.0"

[dependencies]
mirai-annotations = { path = "../../mirai-annotations" }

[features]
default = ["std"]
std = [
]
