[package]
name = "borrow-graph"
version = "0.0.1"
authors = ["Libra Association <opensource@libra.org>"]
publish = false
edition = "2018"
license = "Apache-2.0"

[dependencies]
mirai-annotations = "1.10.1"
sp-std = "2.0.0"
